### ISSUE TITLE
Does not support separate controller and multiple computes

### ISSUE THREAD

**Issue by fultonj** [fultonj/nova_dirsvc_plugin#1]
This was developed on an all-in-one install, where the controller and compute are on the same machine. However, after installing this plugin on a controller node with a separate compute node, I only see the following in the logs so we have a missing mac address. 

```
'Registering instance with directory service at 2015-03-22 13:51:48.149548'
{   'image_uuid': u'36038867-2030-457e-bf0e-9f92c0f2981d',
    'instance_uuid': '85fc9847-c201-43e1-95ef-f42acf5e0335',
    'mac_address': '',
    'project_name': u'admin',
    'user_name': u'admin',
    'user_remote_address': '172.16.2.105'}
```

**Comment by styk-tv** [comment]
Appending:

This ended up a valid question for the older "Icehouse" version. There was no default decorator on the def delete in /usr/lib/python2.7/dist-packages/nova/compute/api.py  after decorator added and nova services restarted messages started showing up in the log

`
'Unregistering instance from directory service at 2016-06-27 11:14:02.297161'
{   'instance_uuid': 'd242a9cd-f83d-4f70-a5a7-521871cb54a9'}
`

Thank you for this example. Can be closed (you may want to add this note to readme.md) Cheers.

**Comment by fultonj** [comment]
Thanks. Closing issue.
